#!/bin/env bash
set -e

if [ -z ${1+x} ]; then
    echo "Build mode argument is required."
    echo "    ./test [build_mode]"
    echo "            debug"
    echo "            release"
    exit 1
fi

EXE="target/$1/patina"

if [ "$1" == "release" ]; then
    cargo build --release
else
    cargo build
fi

Xephyr :2 -ac -br -noreset -screen 800x600 &
sleep 0.25
DISPLAY=:2.0
$EXE 2>&1 &
xterm &